spring.application.name=Todo_Management_Project
spring.datasource.url=jdbc:mysql://localhost:3306/amitdb
spring.datasource.username=root
spring.datasource.password=#Am!t$1212
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format=true
spring.security.user.name=AmitKr
spring.security.user.password=Amit123@123#
spring.security.user.role=ADMIN,USER,MANAGER
